import Head from "next/head";
import Link from "next/link";
import { sanityClient, urlFor } from "../lib/sanity";

const recipesQuery = `*[_type == "recipe"]{
  _id,
  name,
  slug,
  mainImage,
  chef-> {
    _id,
    name,
    image,
  },
  likes
}`;

export default function Home({ recipes }) {
  return (
    <div>
      <Head>
        <title>Oliver&apos;s Kitchen</title>
        <meta name="description" content="Generated by next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>Welcome to Oliver&apos;s Kitchen </h1>

      <ul className="recipes-list">
        {recipes?.length > 0 &&
          recipes.map((recipe) => (
            <li key={recipe._id} className="recipe-card">
              <Link href={`/recipes/${recipe.slug.current}`}>
                <a>
                  <div className="chef-info">
                    <img
                      src={urlFor(recipe?.chef?.image).url()}
                      alt={recipe.chef.name}
                    />
                    <span>Chef | {recipe.chef.name}</span>
                  </div>
                  <div>
                    <img
                      src={urlFor(recipe.mainImage).url()}
                      alt={recipe.name}
                      title={recipe.title}
                    />
                    <div className="overlay"></div>
                  </div>
                  <div className="recipe-wrap-name">
                    <span>{recipe.name}</span>
                    <span className="recipe-likes"> {recipe.likes} ❤️</span>
                  </div>
                </a>
              </Link>
            </li>
          ))}
      </ul>
    </div>
  );
}

export async function getStaticProps() {
  const recipes = await sanityClient.fetch(recipesQuery);
  return {
    props: {
      recipes,
    },
  };
}
