import Head from "next/head";
import Link from "next/link";
import { useEffect } from "react";
import { sanityClient, urlFor } from "../lib/sanity";
import { gsap, Power2 } from "gsap/dist/gsap";

const recipesQuery = `*[_type == "recipe"]{
  _id,
  name,
  slug,
  mainImage,
  chef-> {
    _id,
    name,
    image,
  },
  likes
}`;

export default function Home({ recipes }) {

  // const recipesRef = useRef((recipes?.map(() => createRef())))

  // console.log(recipesRef)

  useEffect(() => {
    if(recipes?.length > 0 ){

      gsap.to(".home-title", {
        opacity: "1",
        x: "0",
        scale: "1",
        ease: Power2.easeOut,
        duration: 1,
      })

      gsap.to(".recipe-card:nth-child(1)", {
        opacity: "1",
        x: "0",
        ease: Power2.easeOut,
        duration: 1,
      })
      gsap.to(".recipe-card:nth-child(2)", {
        opacity: "1",
        x: "0",
        ease: Power2.easeOut,
        duration: 1,
      })
      gsap.to(".recipe-card:nth-child(3)", {
        opacity: "1",
        x: "0",
        ease: Power2.easeOut,
        duration: 1,
      })
      gsap.to(".recipe-card:nth-child(4)", {
        opacity: "1",
        x: "0",
        ease: Power2.easeOut,
        duration: 1,
      })
      
    }
   
  },[])


  return (
    <div>
      <Head>
        <title>Oliver&apos;s Kitchen</title>
        <meta name="description" content="Generated by next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1 className="home-title">Welcome to Oliver&apos;s Kitchen </h1>

      <ul className="recipes-list">
        {recipes?.length > 0 &&
          recipes.map((recipe) => (
            <li key={recipe._id}  className="recipe-card">
              <Link href={`/recipes/${recipe.slug.current}`}>
                <a>
                  <div className="chef-info">
                    <img
                      src={urlFor(recipe?.chef?.image).url()}
                      alt={recipe.chef.name}
                    />
                    <span>Chef | {recipe.chef.name}</span>
                  </div>
                  <div className="recipe-mainImage">
                    <img
                      src={urlFor(recipe.mainImage).url()}
                      alt={recipe.name}
                      title={recipe.title}
                    />
                    <div className="overlay"></div>
                  </div>
                  <div className="recipe-wrap-name">
                    <span>{recipe.name}</span>
                    <span className="recipe-likes"> {recipe.likes} ❤️</span>
                  </div>
                </a>
              </Link>
            </li>
          ))}
      </ul>
    </div>
  );
}

export async function getStaticProps() {
  const recipes = await sanityClient.fetch(recipesQuery);
  return {
    props: {
      recipes,
    },
  };
}
